In [ ]:
import numpy as np
import time

print("NUMPY DATA EXPLORER PROJECT\n")

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.arange(1, 11)
arr3 = np.random.randint(1, 100, size=(3, 3))

print("1D Array:", arr1)
print("Range Array:", arr2)
print("2D Random Array:\n", arr3)

print("\nIndexing & Slicing")
print("First element:", arr1[0])
print("Slice (1 to 3):", arr1[1:4])
print("2D Element [1,2]:", arr3[1, 2])

print("\nMathematical Operations")
print("Addition:", arr1 + 10)
print("Multiplication:", arr1 * 2)
print("Square Root:", np.sqrt(arr1))

matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

print("\nAxis-wise Operations")
print("Row-wise Sum:", np.sum(matrix, axis=1))
print("Column-wise Sum:", np.sum(matrix, axis=0))

print("\nStatistical Operations")
print("Mean:", np.mean(arr2))
print("Median:", np.median(arr2))
print("Max:", np.max(arr2))
print("Min:", np.min(arr2))
print("Standard Deviation:", np.std(arr2))

reshaped = arr2.reshape(2, 5)
print("\nReshaped Array:\n", reshaped)

broadcasted = reshaped + 5
print("Broadcasted Array (+5):\n", broadcasted)

np.save("saved_array.npy", arr3)
loaded_array = np.load("saved_array.npy")

print("\nSaved and Loaded Array:\n", loaded_array)

size = 1000000

python_list = list(range(size))
numpy_array = np.arange(size)

start = time.time()
python_list_result = [x * 2 for x in python_list]
python_time = time.time() - start

start = time.time()
numpy_array_result = numpy_array * 2
numpy_time = time.time() - start

print("\nPerformance Comparison")
print("Python List Time:", python_time)
print("NumPy Array Time:", numpy_time)

print("\nConclusion: NumPy is significantly faster than Python lists.")


NUMPY DATA EXPLORER PROJECT

1D Array: [1 2 3 4 5]
Range Array: [ 1  2  3  4  5  6  7  8  9 10]
2D Random Array:
 [[95 48 15]
 [84 34 50]
 [ 2 86 40]]

Indexing & Slicing
First element: 1
Slice (1 to 3): [2 3 4]
2D Element [1,2]: 50

Mathematical Operations
Addition: [11 12 13 14 15]
Multiplication: [ 2  4  6  8 10]
Square Root: [1.         1.41421356 1.73205081 2.         2.23606798]

Axis-wise Operations
Row-wise Sum: [ 6 15]
Column-wise Sum: [5 7 9]

Statistical Operations
Mean: 5.5
Median: 5.5
Max: 10
Min: 1
Standard Deviation: 2.8722813232690143

Reshaped Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Broadcasted Array (+5):
 [[ 6  7  8  9 10]
 [11 12 13 14 15]]

Saved and Loaded Array:
 [[95 48 15]
 [84 34 50]
 [ 2 86 40]]

Performance Comparison
Python List Time: 0.11261653900146484
NumPy Array Time: 0.004365205764770508

Conclusion: NumPy is significantly faster than Python lists.
